### ISSUE TITLE
iptmon and openwrt firmware 22.x

### ISSUE THREAD

**Issue by darrepac** [benisai/Openwrt-Monitoring#1]
Hi

I have read somewhere (openwrt forum I think) that iptmon is not compatible with 22.x firmware.
Do you confirm it and if yes does it make your project useless? 

thx

**Comment by benisai** [comment]
I believe you are correct. My device is on 21.x with iptables and not nf.

**Comment by benisai** [comment]
but yes, IPTmon works with iptables not NF tables.

**Comment by benisai** [comment]
Does not work with nftables

**Comment by benisai** [comment]
https://github.com/benisai/Openwrt-Monitoring/tree/collectd. 

try this branch, it removes iptmon and replaces it with nlbwmon. please install nlbwmon as well.
In the firewall section of collectd, just remove anything related to iptmon (delete the filters) and just leave firewall enabled with no filters.

**Comment by benisai** [comment]
> Hi
> 
> I have read somewhere (openwrt forum I think) that iptmon is not compatible with 22.x firmware. Do you confirm it and if yes does it make your project useless?
> 
> thx

https://github.com/benisai/Openwrt-Monitoring/tree/collectd.

try this branch, it removes iptmon and replaces it with nlbwmon  (process is from another repo -- https://github.com/mstojek/nlbw2collectd/tree/main?tab=readme-ov-file) . 
please install nlbwmon as well.
In the firewall section of collectd, just remove anything related to iptmon (delete the filters) and just leave firewall enabled with no filters.
