### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [benisai/Openwrt-Monitoring#12]
Hello!

I found this project from https://forum.openwrt.org/t/friendly-traffic-monitor-per-ip-plus-historical/30515

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by benisai** [comment]
Good idea! its completely open, clone, do whatever you want. I dont care. 

https://github.com/benisai/Openwrt-Monitoring/blob/main/LICENSE

**Comment by vazhnov** [comment]
The MIT license — awesome!
Thank you!
