### ISSUE TITLE
Router IP , Server IP variable request in prometheus.yml

### ISSUE THREAD

**Issue by akademsubotnik** [benisai/Openwrt-Monitoring#2]
Really cool project, I like especially that per IP data is shown in the dashboard.  
I'm having trouble understanding where to set the Router IP and Server IP in prometheus.yml.  Would it be possible to set them with a variable like in router-setup.sh?

**Comment by benisai** [comment]
Hi, https://github.com/benisai/Openwrt-Monitoring/blob/main/Docker/prometheus.yml 

My Router IP is 10.0.5.1, so replace that with your router IP. 

The server IP in the prometheus.yml file is no longer needed as I pointed the targets to the container names :) 

I will update the readme. Thanks

**Comment by benisai** [comment]
Please check out the new readme. It has been re-worked, I hope it makes sense now.  
I honestly setup this repo for my personal use so I could note down my work for later, but I'm glad to see others using it.

**Comment by akademsubotnik** [comment]
I appreciate it!
