### ISSUE TITLE
Missing docker network

### ISSUE THREAD

**Issue by akademsubotnik** [benisai/Openwrt-Monitoring#3]
docker-compose up -d
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
ERROR: Network internal declared as external, but could not be found. Please create the network manually using `docker network create internal` and try again.

**Comment by benisai** [comment]
Sudo docker network create internal

**Comment by akademsubotnik** [comment]
thanks
