### ISSUE TITLE
Uninstall script?

### ISSUE THREAD

**Issue by jotrocken** [benisai/Openwrt-Monitoring#7]
Hi,

Does anyone of you have an uninstall script to reverse the changes on the router? The uninstallation on the home server is of course not a problem with Docker.
I could just uninstall the packages named in _routersetup.sh_, but I'm unsure about the DNS settings and the made changes on router config files.

Thanks for your help!

**Comment by benisai** [comment]
Go to 
 Luci > Network > Interfaces > lan > DHCP Server > Advanced Settings > DHCP-Options > `1.0.0.1`,6

Remove the IP

**Comment by benisai** [comment]
Closing as this should be resolved
